inference:
  model_filepath: "C:/Users/disis/Repos/AttentionSpan.ai/models/models/20251108model.pt" # Set to correct model file

hydra:
  run:
    dir: .
  output_subdir: null   # Working dir always project root