train:
  lr: 1e-3
  batch_size: 32
  epochs: 10

model:
  n_channels: 4
  n_classes: 3

system:
  accelerator: "cpu"
  devices: 1
  model_output_filepath: "data"

inference:
  weights_filepath: "${system.model_output_filepath}/model/example.pt"

hydra:
  run:
    dir: .
  output_subdir: null   # Working dir always project root