train:
  lr: 1e-3
  batch_size: 32
  epochs: 10
  num_workers: 4

model:
  n_channels: 4   # Input features
  n_classes: 3    # Output categories
  n_outputs: 5    # Output values (regression)
  hidden_dims: [16, 32]
  labels: {"focus":0, "unfocus":1, "fatigue":2}

system:
  accelerator: "cpu"
  devices: 1
  data_filepath: "data"
  model_output_filepath: "models"

hydra:
  run:
    dir: .
  output_subdir: null   # Working dir always project root