train:
  lr: 1e-3
  batch_size: 32
  epochs: 10

model:
  n_channels: 4
  n_classes: 2

system:
  accelerator: "cpu"
  devices: 1
  model-filepath: data"

hydra:
  run:
    dir: .
  output_subdir: null