train:
  lr: 1e-3
  batch_size: 32
  epochs: 10
  num_workers: 4

model:
  n_channels: 11 # Input features (waves, gyro)
  n_classes: 4 # Output categories (#labels) (classification)
  n_outputs: 4 # Output values (probably #labels) (regression)
  hidden_dims: [16, 32]
  labels: { "focus": 0, "unfocus": 1, "fatigue": 2 }
  channel_labels: [Delta,Theta,Alpha,Beta,Gamma,GyroX,GyroY,GyroZ,AccelX,AccelY,AccelZ]

system:
  accelerator: "cpu"
  devices: 1
  data_filepath: "data"
  model_output_filepath: "models"

hydra:
  run:
    dir: .
  output_subdir: null # Working dir always project root
